### ISSUE TITLE
Unified navigation across our sites

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/rfcs#97]
Suggested by @fantasai in https://twitter.com/fantasai/status/1438998571311841281:

> Would be really nice if WPT would have some kind of unified navigation banner across all its websites.
>
> Y'know, level up from undifferentiated some-people-wrote-useful-scripts chaos to some quality late 1990s UX.

I think this is a good idea. For wpt.live there is a challenge of not messing with reftests, but we could at least do it for all directories, including the root.

cc @KyleJu

**Comment by m0dulev1** [comment]
Ty

**Comment by zcorpan** [comment]
Here's a mockup I made in devtools. It needs tweaks to work on mobile/narrow viewport.

Longdesc: At the top of the page there's a dark blue navigation bar. On the left, a white WPT logo. Then 3 links:
- Docs `web-platform-tests.org`
- Test results `wpt.fyi`
- Live tests `wpt.live`

The current page is highlighted with a lighter background color.

<img width="1070" alt="Screenshot of web-platform-tests.org mockup" src="https://user-images.githubusercontent.com/244772/152515368-6dee7bc0-99a3-49ac-9938-57e8d149487d.png">
<img width="1070" alt="Screenshot of wpt.fyi mockup" src="https://user-images.githubusercontent.com/244772/152515381-cf20fa10-e4b9-46f9-a16d-3fda03554101.png">
<img width="1070" alt="Screenshot of wpt.live mockup" src="https://user-images.githubusercontent.com/244772/152515387-697b1319-bce9-4628-b2e0-a1a81a312e21.png">

The injected HTML on wpt.fyi is
```html
<nav style="
    background: #003C56;
    min-height: 40px;
    font: 16px Georgia, serif;
    margin: 0 -16px;
"><img alt="WPT" src="https://raw.githubusercontent.com/web-platform-tests/wpt/master/images/wpt-logo/wpt-logo-white.svg" width="40" height="40" style="
    vertical-align: middle;
    padding: 5px 1em;
    display: inline-block;
    color: white;
"><a href="https://web-platform-tests.org/">Docs <code>web-platform-tests.org</code></a> <a href="https://wpt.fyi/" class="current">Test results <code>wpt.fyi</code></a> <a href="http://wpt.live">Live tests <code>wpt.live</code></a></nav>
```
Added CSS:
```css
nav a:focus, nav a:hover {
    color: black;
    background: #eee;
}
nav a {
    color: white;
    padding: 1em;
    text-decoration: underline;
}
nav a * {
    color: inherit;
}
nav code {
    font-family: 'Consolas', 'Menlo', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', monospace;
    font-size: 0.9em;
    font-weight: bold;
}
nav .current {
    background: rgb(26.27% 44.04% 55.33%);
}
```
